Integrate search theorem into article
mimosa-project/emwiki pull request #207
Opened 2021-11-23 12:59 UTC by g063ff

## 目的
Articleアプリケーションに定理検索を統合する。
## 関連するIssue等
+ 

## レビューポイント
+ 従来の定理検索アプリケーションを削除しました。
+ getパラメータ(?target=theorem)を与えてarticleアプリケーションを開くとdrawerで定理検索が行えるようにしました

## 留意事項
+ 

## 残課題
+

2021-11-23 14:26 UTC, etmula requested changes
いくつか質問をしているので、回答お願いします。

2021-11-23 14:26 UTC, etmula commented on emwiki/article/static/article/js/views/ArticleView.js
> +        await this.reloadArticle(newRoute.params.name.replace('.html', ''))
補足: 定理検索の結果をクリックしてArticleがロードされるときにhashの位置がおかしい問題を修正

2021-11-23 14:26 UTC, etmula commented on emwiki/article/templates/article/index.html
> +<script src="{% static 'search/js/components/theoremDrawer.js'%}"></script>
theoemDrawer -> TheoremDrawer
ArticleDrawer, SymbolDrawerなどと合わせる

2021-11-23 14:26 UTC, etmula commented on emwiki/search/static/search/js/components/theoremDrawer.js
> +          </div>
v-forをv-cardに付けずに、divを作成してv-forを付けているいる理由はなんですか？

2021-11-23 14:26 UTC, etmula commented on emwiki/search/static/search/js/components/theoremDrawer.js
> +      <div v-if="!isAscii" class="alert alert-danger m-3" role="alert">Search text allows ascii characters only</div>
v-textareaのerror propsを利用する
https://vuetifyjs.com/ja/api/v-textarea/#props-error

2021-11-23 14:26 UTC, etmula commented on emwiki/search/static/search/js/components/theoremDrawer.js
> +      this.searchHeight = document.getElementsByTagName('body')[0].clientHeight - document.getElementById('search-btn').getBoundingClientRect().bottom
FlexなElementであれば検索結果表示枠の高さを計算する必要はないように思うのですが、なぜ手動で計算しているのですか？
画像などあれば嬉しいです。

2021-11-23 14:26 UTC, etmula commented on emwiki/search/static/search/js/components/theoremDrawer.js
> +        hash = linkAndHash[1]
constをつける

2021-11-23 14:26 UTC, etmula commented on emwiki/search/static/search/js/components/theoremDrawer.js
> +        this.$router.push({ name: 'Article', params: { name: filename }, hash: '#' + hash, query: { target: 'theorem' }})
わざわざhash変数を作っているのであれば、👆で'#' + hashをしてしまっても良いかも

2021-11-23 14:26 UTC, etmula commented on emwiki/search/static/search/js/components/theoremDrawer.js
> +        console.log("aas")
消す

2021-11-24 06:44 UTC, g063ff commented on emwiki/search/static/search/js/components/theoremDrawer.js
> +          </div>
表記ズレを防ぐために行っていたつもりでしたが、
確認したところdivは不要だったので修正します。

2021-11-24 06:47 UTC, g063ff commented on emwiki/search/static/search/js/components/theoremDrawer.js
> +      this.searchHeight = document.getElementsByTagName('body')[0].clientHeight - document.getElementById('search-btn').getBoundingClientRect().bottom
![emwiki](https://user-images.githubusercontent.com/60038502/143187893-62cda9a6-9236-4e29-b26b-61b65831e255.png)左側の検索結果表示枠にスクロールバーを実装するためには、その要素の高さを指定する必要があったので計算しています

2021-11-24 16:44 UTC, etmula approved these changes
LGTM!

2021-11-24 16:44 UTC, etmula commented on emwiki/search/static/search/js/components/TheoremDrawer.js
> +  </div>`,
検索結果一覧がカードになっていて、線が増え余計なclass styleが増えている様に思います。
以下のように、配列の表示にはListを用いたほうが自然だと思います。
また、heightやoverflowなど、基本的なstyle属性はVuetifyのPropsで提供されているので、使用する前にdocumentで検索することをおすすめします。
```
<div>
      <v-form>
        <v-textarea
          outlined
          name="search"
          label="search theorem"
          v-model="searchText"
          @keydown.shift.enter="search(searchText)"
          class="pt-10"
        >
        </v-textarea>
        <v-btn v-if="loading" block disabled>
          <v-progress-circular indeterminate color="primary" />
        </v-btn>
        <v-btn v-else block @click="search(searchText)" id="search-btn">Search</v-btn>
      </v-form>
      <v-list :height="searchHeight" class="overflow-auto">
        <v-list-item-group>
          <v-list-item
            v-for="TheoremModel in TheoremModels"
            :key="TheoremModel.id"
            @click.once="recordReactions(TheoremModel.id, 'url')"
            @click="loadArticle(TheoremModel.url)"
          >
            <v-list-item-content v-bind:name="TheoremModel.id">
              <v-card-title class="d-flex justify-space-between">
                $(TheoremModel.label)
                <v-chip color="secondary" small>
                  relevance: $(TheoremModel.relevance)
                </v-chip>
                <v-btn @click="recordReactions(TheoremModel.id, 'fav')" v-bind:id="'fav-btm-' + TheoremModel.id">
                  <v-icon color="blue">mdi-thumb-up</v-icon>
                </v-btn>
              </v-card-title>
              <v-card-text><code>$(TheoremModel.text)</code></v-card-text>
            </v-list-item-content>
          </v-list-item>
        </v-list-item-group>
      </v-list>
      </div>
    </div>
```
![image](https://user-images.githubusercontent.com/49423101/143279720-325d2882-4cc4-4bb2-91bc-b746174baac1.png)

2021-11-24 16:49 UTC, etmula commented on emwiki/search/static/search/js/components/TheoremDrawer.js
> +  </div>`,
検索結果の高さ削減(一画面により多くの結果を表示できる)
検索結果のfileを削除(タイトルと同義だったため)
SubscribeボタンをTitleと同じ行に統合
Codeを`<code>`要素で囲んで背景を変更
relevanceをv-chipに変更(タイトルと見た目を区別するため)
Cardの配列をListに変更(無駄な線が消え、可読性が向上)
form郡をv-formで囲んだ(@submitやerrorなどのeventをハンドルできる)

2021-11-25 06:20 UTC, etmula commented on emwiki/search/static/search/js/components/TheoremDrawer.js
> +      </v-btn>
```
<v-btn
  id="search-btn"
  block
  @click="search(searchText)"
  :disabled="!$refs.searchForm.validate()"
>
  Search<v-progress-circular indeterminate v-if="loading" color="primary" />
</v-btn>
```

2021-11-25 06:31 UTC, etmula commented on emwiki/search/static/search/js/components/TheoremDrawer.js
> +          @click="loadArticle(TheoremModel.url)"
@click.self(maybe)
https://jp.vuejs.org/v2/guide/events.html#%E3%82%A4%E3%83%99%E3%83%B3%E3%83%88%E4%BF%AE%E9%A3%BE%E5%AD%90

2021-11-25 06:48 UTC, g063ff commented on emwiki/search/static/search/js/components/TheoremDrawer.js
> +    articleHeight: 0,
消す

2021-11-25 06:48 UTC, g063ff commented on emwiki/search/static/search/js/components/TheoremDrawer.js
> +      const regex = new RegExp(/^[\x20-\x7e\s]*$/);
あらかじめ宣言しておく

2021-11-25 06:48 UTC, g063ff commented on emwiki/search/static/search/js/components/TheoremDrawer.js
> +    TheoremModels: [],
小文字はじまりにする

2021-11-25 06:48 UTC, g063ff commented on emwiki/article/static/article/js/views/ArticleView.js
>      },
Comment.bulkFetch(article, comments, context['comments_uri']);に戻す

2021-11-25 06:48 UTC, g063ff commented on emwiki/search/static/search/js/components/TheoremDrawer.js
> +    recordReactions(id, buttonType) {
色を変更する

2021-11-25 06:48 UTC, g063ff commented on emwiki/search/static/search/js/components/TheoremDrawer.js
> +      TheoremService.recordReactions(id, buttonType);
👍ボタンのみが押されたときにロードされないようにする

2021-11-25 06:48 UTC, g063ff commented on emwiki/search/static/search/js/components/TheoremDrawer.js
> +          v-for="TheoremModel in TheoremModels"
先頭を小文字に直す

2021-11-25 06:48 UTC, g063ff commented on emwiki/search/static/search/js/services/theorem-service.js
> +   * @return {Array<Object>} search results
{Promise\<Array\>}

2021-11-25 06:48 UTC, g063ff commented on emwiki/search/static/search/js/services/theorem-service.js
> +  static searchTheorem(searchText) {
引数でcontext['search_uri']を受け取る

2021-11-25 06:48 UTC, g063ff commented on emwiki/search/static/search/js/services/theorem-service.js
> +  static recordReactions(id, buttonType) {
引数でcontext['search_uri']を受け取る

2021-11-25 06:48 UTC, g063ff commented on emwiki/search/static/search/js/services/theorem-service.js
> +    const csrftoken = Cookies.get('csrftoken');
csrftokenも引数で受け取る

2021-11-25 10:05 UTC, aabaa requested changes

2021-11-25 10:05 UTC, aabaa commented on emwiki/search/static/search/js/components/TheoremDrawer.js
> +const regex = new RegExp(/^[\x20-\x7e\s]+$/);
大文字でPRINTABLE_STRING_REGなどとしてください
また，一番外側に書いてしまうと変数スコープがグローバルになってしまうのではないでしょうか？

2021-11-25 10:43 UTC, g063ff commented on emwiki/search/static/search/js/components/TheoremDrawer.js
> +const regex = new RegExp(/^[\x20-\x7e\s]+$/);
グローバルになってしまっていたので, 名前を変更しVueのdata内に移動しました

2021-11-25 11:07 UTC, merged