Improve processing of article page transitions
mimosa-project/emwiki pull request #233
Opened 2021-12-15 08:17 UTC by Furushiima

## 目的
#229 と #230 を解決する
dataとwatchからhashを削除し、routeのwatch内ですべてのページ遷移の処理を書き換えて解決しました。
## 関連するIssue等
+ fix #229 
+ fix #230 

## レビューポイント
+ 

## 留意事項
+ 

## 残課題
+

2021-12-15 10:16 UTC, yamamichid commented on emwiki/article/static/article/js/views/ArticleView.js
> +    scrollToHash(hash) {
scrollだけではなく、backgroundColorの変更も行なっているので、誤解を招くかもしれません。
`navigateToHash`, `highlightAndScrollToHash`,など?

2021-12-15 10:16 UTC, yamamichid commented on emwiki/article/static/article/js/views/ArticleView.js
> +    scrollToHash(hash) {
1度しか実行されておらず、実行場所も限られるため、今はmethodとして作成する必要はないかもしれません。

2021-12-15 13:24 UTC, Furushiima commented on emwiki/article/static/article/js/views/ArticleView.js
> +          oldHashElement.style.backgroundColor = 'white';
アーティクル名が同じかつoldHashが存在する場合のみ実行しているので大丈夫です。

2021-12-15 13:28 UTC, Furushiima commented on emwiki/article/static/article/js/views/ArticleView.js
> +      } else {
```Javascript
      if (newRoute.params.name !== oldRoute.params.name) {
        await this.reloadArticle(newRoute.params.name.replace('.html', ''));
      } else {
        if (oldRoute.hash) {
          console.log("aas");
          const oldHashElement =
            document.getElementsByName(oldRoute.hash.split('#')[1])[0];
          oldHashElement.style.backgroundColor = 'white';
        }
      }
```
なので同じページ内でのHash変更時にのみ実行しています。

2021-12-15 13:36 UTC, Furushiima commented on emwiki/article/static/article/js/views/ArticleView.js
> +    scrollToHash(hash) {
確かに他の処理もしているので名前は変えたほうが良いですね。
実行が一回だけなのでメソッド化はやめようと思います。

2021-12-15 15:44 UTC, yamamichid commented on emwiki/article/static/article/js/views/ArticleView.js
> +      } else {
勘違いでしたすみません

2021-12-15 15:44 UTC, yamamichid commented on emwiki/article/static/article/js/views/ArticleView.js
> +          oldHashElement.style.backgroundColor = 'white';
アーティクル名が同じかつoldHashが存在し、oldHashの要素がない場合にエラーが発生するとおもいます。
```
const oldHashElements = document.getElementsByName(oldRoute.hash.split('#')[1]);
if(oldHashElements.length > 0){
    oldHashElements[0].style.backgroundColor = 'white';
}
```
で回避できると思います。
また、その場合`scrollToHash`メソッドでも同じことが言えると思うので、そちらも修正する必要があるかと思います。
ArticleのHTMLは自前ではないので、あらゆることが保証されていないことに注意してください。

2021-12-15 15:44 UTC, yamamichid commented on emwiki/article/static/article/js/views/ArticleView.js
> +          oldHashElement.style.backgroundColor = 'white';
`oldRoute.hash.split('#')[1]`は、`oldRoute.hash.replace('#', '')`のほうが自然かと思います。

2021-12-16 00:46 UTC, Furushiima commented on emwiki/article/static/article/js/views/ArticleView.js
> +          oldHashElement.style.backgroundColor = 'white';
確かにそうですね。変更します。

2021-12-16 02:10 UTC, Furushiima commented on emwiki/article/static/article/js/views/ArticleView.js
> +    scrollToHash(hash) {
mountedのthis.reloadArticleのthen()で呼び出す必要があったのでやっぱり名前をnavigateToHashに変更してメソッド化しようと思います。

2021-12-16 08:22 UTC, aabaa requested changes

2021-12-16 08:22 UTC, aabaa commented on emwiki/article/static/article/js/views/ArticleView.js
> +        document.getElementsByName(hash.replace('#', ''))[0];
先に空配列ではないことをチェックしてから[0]でアクセスする

2021-12-16 09:38 UTC, aabaa requested changes

2021-12-16 09:38 UTC, aabaa commented on emwiki/article/static/article/js/views/ArticleView.js
> +          }
[0]でアクセスする前にlengthを確認してください

2021-12-17 00:13 UTC, merged