Add splitter
mimosa-project/emwiki pull request #238
Opened 2022-01-06 09:08 UTC by Furushiima

## 目的
サイドバーの幅を調整するための、splitterコンポーネントを作成しました。
## 関連するIssue等
+ close #157 

## レビューポイント
+ ArticleのApp.jsではdrawerWidth(サイドバーの幅)の値をマウントされる前に決定する必要があったのでcreated()に変更しています。

## 留意事項
+ 

## 残課題
+

2022-01-11 06:09 UTC, yamamichid requested changes
変更後のGif画像を添付してもらえると，とてもありがたいです．

2022-01-11 06:09 UTC, yamamichid commented on emwiki/static/js/splitter.js
> +export const splitter = {
componentはupper camel caseで統一してください．

2022-01-11 07:47 UTC, Furushiima commented on emwiki/static/js/splitter.js
> +export const splitter = {
すみません。修正します。

2022-01-11 07:48 UTC, Furushiima commented
変更後のGifです。
![emwikiPR238](https://user-images.githubusercontent.com/60038502/148901776-7d8bef88-cd9c-4701-9be4-c31f8094f783.gif)

2022-01-13 03:58 UTC, aabaa requested changes

2022-01-13 03:58 UTC, aabaa commented on emwiki/static/js/Splitter.js
> +    drawer: Boolean,
drawer -> drawerExists

2022-01-13 03:58 UTC, aabaa commented on emwiki/static/js/Splitter.js
> +      @mousedown="startChangeWidth"
シングルクォーテーションに変更

2022-01-13 05:07 UTC, merged