Add searcher of mml reference
mimosa-project/emwiki pull request #246
Opened 2022-01-29 15:35 UTC by Furushiima

## 目的
ArticleとSymbolのサイドバーの検索アルゴリズムをMML Referenceのものに戻しました。
## 関連するIssue等
+ Fix #209 

## レビューポイント
+ 

## 留意事項
+ 

## 残課題
+

2022-01-31 10:11 UTC, yamamichid requested changes
非同期関数について理解をより深めたほうがいいでしょう．(async Promise)
また，Array.prototypeに属している関数の使い所を一度すべて見てみたほうがいいと思います．

2022-01-31 10:11 UTC, yamamichid commented on emwiki/article/static/article/js/components/ArticleDrawer.js
> +        this.searchResult.push(article);
通常map関数は値の型を変化させるために用いる．
繰り返し処理がしたいのであれば`forEach`を用いる．
https://developer.mozilla.org/ja/docs/Web/JavaScript/Reference/Global_Objects/Array/map#when_not_to_use_map
```js
this.items = resultList
this.items.forEach(item => item.name = this.highlight(item.name, this.query))
```

2022-01-31 10:11 UTC, yamamichid commented on emwiki/article/static/article/js/components/ArticleDrawer.js
> +    items: [],
この3つの変数は共通の要素を持っているにも関わらず名前に統一性がない．
index: 全てのArticle名のリスト
searchResult: 検索結果のArticle名のリスト
items: サイドバーに表示するArticle名のリスト

searchResultとitemsの意味合いがほぼ同じなのでどちらか消せそうと考える．
それぞれ，`articleNames`, `articleNamesFiltered`などにしたほうが良い

2022-01-31 10:11 UTC, yamamichid commented on emwiki/symbol/static/symbol/js/components/SymbolDrawer.js
>  };
ArticleDrawerをみて同じ様に修正してください

2022-01-31 11:03 UTC, Furushiima commented
ありがとうございます。確認します。

2022-01-31 11:39 UTC, Furushiima commented on emwiki/article/static/article/js/components/ArticleDrawer.js
> +    // searcher.runで非同期で処理される関数
この関数自体は同期関数で問題なくて, この関数を呼び出している関数(Searcher.jsのrunの中のrunner)が非同期で呼び出されています.

2022-01-31 11:56 UTC, Furushiima commented on emwiki/article/static/article/js/components/ArticleDrawer.js
> +      }
もともとその方法を検討していたのですが、例えばクエリが
```
'a' => ''
```
と変化した際には
```javascript
this.searcher.run(newQuery, this.updateSearchResults);
this.items = this.index;
```
という処理の流れになるのですがthis.searcher.runの中でthis.updateSearchResultsが非同期に呼ばれていて、this.updateSearchResultsではthis.itemに検索結果をpushしているので、
this.itemsがthis.indexを指した後に検索結果がpushされ、itemsの中にarticleが2重で入ってしまうというケースがありました。
なので, 3つ下のコメントのように
```
index: 全てのArticle名のリスト
searchResult: 検索結果のArticle名のリスト
items: サイドバーに表示するArticle名のリスト
```
の3つのリストを使用しています。

2022-01-31 15:45 UTC, yamamichid commented on emwiki/article/static/article/js/components/ArticleDrawer.js
> +    // searcher.runで非同期で処理される関数
ではこのコメントは何を伝えたいんですか?
また呼び出される側に呼び出す側の情報を書くことは基本的に有りません．
どの親からも呼び出せる関数であれば，どの親から呼び出されてもその関数の責任を果たせるように実装すべきだと思います．

2022-01-31 15:52 UTC, yamamichid commented on emwiki/article/static/article/js/components/ArticleDrawer.js
> +      }
------
もともとその方法を検討していたのですが、例えばクエリが
```
'a' => ''
```
と変化した際には
```
this.searcher.run(newQuery, this.updateSearchResults);
this.items = this.index;
```
という処理の流れになる

------
の部分がコードと矛盾している様に見えるのですが合ってますか?
(以下のコード部について)
```python
if (newQuery !== '') {
 ...
} else {
  this.items = this.index;
}
```

2022-01-31 16:07 UTC, Furushiima commented on emwiki/article/static/article/js/components/ArticleDrawer.js
> +    // searcher.runで非同期で処理される関数
この関数が非同期に呼ばれることによって下のコメント(https://github.com/mimosa-project/emwiki/pull/246#discussion_r795599460)のような問題が起こったので、
「この関数はsearcher.runによって非同期に処理される」ということを伝えたほうが良いと考え、コメントしました。

2022-01-31 16:13 UTC, Furushiima commented on emwiki/article/static/article/js/components/ArticleDrawer.js
> +      }
紛らわしい書き方をしてしまってすみません。
クエリが'a'のときに
```js
this.searcher.run(newQuery, this.updateSearchResults);
```
が呼ばれ、
クエリが''に変更されたときに
```
this.items = this.index;
```
が呼ばれるという意味です。この動作が高速に行われると上記の問題が発生します

2022-02-01 13:42 UTC, yamamichid commented on emwiki/article/static/article/js/components/ArticleDrawer.js
> +      }
Searchクラスの中のどの箇所で非同期処理が呼ばれていますか?
また，こちらのローカルで再現できなかったので再現する方法を教えて下さい．

2022-02-01 13:46 UTC, yamamichid commented on emwiki/article/static/article/js/components/ArticleDrawer.js
> +    // searcher.runで非同期で処理される関数
```
この関数自体は同期関数で問題なくて, この関数を呼び出している関数(Searcher.jsのrunの中のrunner)が非同期で呼び出されています.
```
は
```
この関数を呼び出している関数(Searcher.jsのrunの中のrunner)**から**非同期で呼び出されています.
```
の間違いですか?

2022-02-01 13:54 UTC, yamamichid commented on emwiki/article/static/article/js/components/ArticleDrawer.js
> +    // searcher.runで非同期で処理される関数
「この関数はsearcher.runによって非同期に処理される」ということを伝えられて開発者はどの様に考えこの関数を読み変更し削除する判断をすればよいのですか?

2022-02-01 16:55 UTC, Furushiima commented on emwiki/article/static/article/js/components/ArticleDrawer.js
> +    // searcher.runで非同期で処理される関数
非同期で呼びだすというのは、非同期で呼び出された関数はその処理が終了しなくても次のコードが実行されるという認識であってますか？（これが違ったら下の文は無視してください...）

- updateSearchResultsは同期関数
 - updateSearchResultsはsearcher.run内のrunnerで同期的に呼び出される(updateSearchResultsが終わるまで次の行に行かない)
 - searcher.run内のrunnerは自分自身を非同期で呼び出している
 
ので、updateSearchResultsはSearcher.jsのrunの中のrunner**から**非同期で呼び出されているわけではないと思います。。

// searcher.runで非同期で処理される関数
それだと、このコメントはおかしいですね...

2022-02-01 17:06 UTC, Furushiima commented on emwiki/article/static/article/js/components/ArticleDrawer.js
> +      }
213行目です。

https://user-images.githubusercontent.com/60038502/152014890-85dce21a-3e9f-4fca-bbc9-696b08e5b5c5.mp4

分かりやすいようにフッターをつけています。indexは1358件なのですが
'dfgd' => 'dfg' => 'df'=> 'd' => ''と高速で検索クエリが空文字になるとitemsがindexを指した後に, 検索結果がpushされ2234件もアーティクルがitemsに格納されています。

2022-02-02 15:43 UTC, yamamichid commented on emwiki/article/static/article/js/components/ArticleDrawer.js
> +    // searcher.runで非同期で処理される関数
下の記事参考読んでみて
https://qiita.com/ryosuketter/items/dd467f827c1b93a74d76
https://qiita.com/KickJune/items/3e980d00102c5c7cf600

2022-02-02 17:10 UTC, yamamichid commented on emwiki/article/static/article/js/components/ArticleDrawer.js
> +    // searcher.runで非同期で処理される関数
```js
query(newQuery) {
      this.searcher.run(
          newQuery,
          (items) => this.items = items,
          (items) => items.forEach((item) => this.items.push(item)) );
    },
```

2022-02-02 17:11 UTC, yamamichid commented on emwiki/article/static/article/js/components/ArticleDrawer.js
> +    // searcher.runで非同期で処理される関数
Searcherにhighlightを追加し，`searchInChunk`内でハイライトを処理した

2022-02-02 17:12 UTC, yamamichid commented on emwiki/article/static/article/js/components/ArticleDrawer.js
> +    // searcher.runで非同期で処理される関数
JSだと参照渡し出来ないからこういうときはよくラムダ関数渡す

2022-02-03 15:27 UTC, Furushiima commented on emwiki/article/static/article/js/components/ArticleDrawer.js
> +    // searcher.runで非同期で処理される関数
ありがとうございます。非同期処理の理解浅かったです。。
setResultsとpushResultsをその場で定義して渡す発想がなかったです...
余計な関数をArticleDrawerに定義せずにすっきり書けるのでそうします。

searchInChunk内でハイライトを処理を行うのであれば、mml referenceのようにSearcherの内部にhighlightの処理も書いてしまった方が、良さそうなのでそちらも修正しようと思います。（現在SearcherとHighlighterを分けるために同じ処理を2重で書いてしまっている部分があるので...）

2022-02-10 06:05 UTC, yamamichid commented on emwiki/article/static/article/js/components/ArticleDrawer.js
> +            </p>
<p 
  class="m-0 p-2" 
  v-html="queryText==='' ? props.item.name : props.item.highlightedName"
>
</p>

2022-02-10 06:07 UTC, yamamichid commented on emwiki/symbol/static/symbol/js/components/SymbolDrawer.js
> +    highlighter: null,
highlighter: new Highlighter(),

2022-02-10 06:08 UTC, yamamichid approved these changes

2022-02-17 08:30 UTC, aabaa approved these changes

2022-02-17 08:30 UTC, merged