Use natural sort for index
mimosa-project/emwiki pull request #248
Opened 2022-01-29 16:19 UTC by Furushiima

## 目的

## 関連するIssue等
+ Fix #247 

## レビューポイント
+ 

## 留意事項
+ 

## 残課題
+

2022-01-31 10:15 UTC, yamamichid requested changes

2022-01-31 10:15 UTC, yamamichid commented on emwiki/article/views.py
> +        articles = humansorted(articles, key=lambda a: a.name)
変数の意味が途中で変わる事はあまり望ましくない
```python
articles = humansorted(list(Article.objects.all()), key=lambda a: a.name)
```

2022-01-31 10:15 UTC, yamamichid commented on emwiki/symbol/views.py
> +        symbols = humansorted(symbols, key=lambda a: a.name)
```python
symbols = humansorted(list(Symbol.objects.all()), key=lambda a: a.name)
```

2022-01-31 12:13 UTC, Furushiima commented
ありがとうございます。修正しました。

2022-02-17 08:06 UTC, aabaa approved these changes

2022-02-17 08:06 UTC, merged