Remove jQuery
mimosa-project/emwiki pull request #267
Opened 2022-03-08 14:48 UTC by Furushiima

## 目的
jQueryを削除する
## 関連するIssue等
+ #222 

## レビューポイント
+ Articleのコメント部分にjQueryを使った記述が残っていたので, Javascriptで書き換えました。

## 留意事項
+ 

## 残課題
+

2022-03-08 15:05 UTC, Furushiima commented on emwiki/article/static/article/js/models/comment.js
> -      }
ログインしていない状態でコメントを送信(例えばeditボタンを押したまま別タブでログアウトしてコメントを送信等)した場合、
リダイレクトされ、このif文は実行されないので削除しました
![emwiki-302](https://user-images.githubusercontent.com/60038502/157264226-bc7a3172-12dc-4e99-8418-bdf2bd89aa6c.PNG)

2022-03-10 01:17 UTC, yamamichid approved these changes

2022-03-10 05:27 UTC, aabaa requested changes

2022-03-10 05:27 UTC, aabaa commented on emwiki/article/static/article/js/models/editor.js
> +    return this.element.getElementsByClassName('commentTextarea')[0].value;
optional chainingを使う
return this.element.getElementsByClassName('commentTextarea')[0]?.value;

2022-03-10 15:01 UTC, Furushiima commented on emwiki/article/static/article/js/models/editor.js
> +    }
Optional Chainingは左辺では使えないようです。
コードの分量が増えてしまいますが、if文でチェックしています。他の部分も同様です。

2022-03-11 01:18 UTC, aabaa approved these changes

2022-03-11 01:18 UTC, merged