Improve search algorithm
mimosa-project/emwiki pull request #294
Opened 2023-02-28 05:34 UTC by Furushiima

## 目的
- 定理検索アルゴリズムを型情報を考慮するように変更
- それに伴いemparserをmizcoreに置き換え
## 関連するIssue等
+ 

## レビューポイント
+ 

## 留意事項
+ [Mizacoreの変更](https://github.com/mimosa-project/mizcore/pull/31)を含んでいます

## 残課題
+

2023-03-02 08:12 UTC, aabaa requested changes

2023-03-02 08:12 UTC, aabaa commented on emwiki/search/parse_abs.py
> +                processed_text += "___" + " "
関数化してresolve_variable_declaration_statement_text()の重複コードを消す

2023-03-02 08:12 UTC, aabaa commented on emwiki/search/parse_abs.py
> +def process_for_search_word(query):
transform_query_for_search

2023-03-02 08:12 UTC, aabaa commented on emwiki/search/parse_abs.py
> +def process_for_search_word(query):
他に良い名前がないか考える

2023-03-05 05:02 UTC, Furushiima commented on .flake8
> +ignore = E501,W503
長い行を改行する場合に, 演算子の前で改行を行うとがW503発生し, 演算子の後で改行を行うとがW504発生するため, W503を無効化しました

https://rcmdnk.com/blog/2019/11/04/computer-python/

2023-03-07 06:16 UTC, aabaa requested changes

2023-03-07 06:16 UTC, aabaa commented on emwiki/search/parse_abs.py
> +def replace_variable_with_type(tokens, common_variables):
variableとtype(=tokens)の対応マッピングを作成する処理とテキスト生成を別関数に分割する

2023-03-07 06:16 UTC, aabaa commented on emwiki/search/parse_abs.py
> +def replace_variable_with_type(tokens, common_variables):
variable.ref_tokenがNoneか否かで変数宣言か否かをチェックする

2023-03-09 05:33 UTC, aabaa requested changes

2023-03-09 05:33 UTC, aabaa commented on emwiki/search/parse_abs.py
> +    return variables
```python
reserve_statements: list[list[Token]] = []
# reserveで始まる文をreserve_statementsに集める

for reserve_statement : list[Token] in reserve_statements:
  # 処理
```

2023-03-09 05:33 UTC, aabaa commented on emwiki/search/parse_abs.py
> +    処理後: let RelStr be RelStr  attr RelStr is Noetherian means the InternalRel of RelStr is co-well_founded   ____
変数宣言の型を取ってくる処理を関数化する

2023-03-16 05:01 UTC, aabaa requested changes

2023-03-20 06:38 UTC, aabaa requested changes

2023-03-20 06:38 UTC, aabaa commented on emwiki/search/parse_abs.py
extract_types_from_in_tokens -> extract_variables_with_type_in_tokens
replace_variable_with_type -> replace_variable_with_type_string
create_common_variables -> listup_reserved_variable2type
create_variables_from_declarations -> listup_declared_variable2type
add_variables -> add_variable2type

2023-03-21 06:31 UTC, aabaa approved these changes

2023-03-21 06:31 UTC, merged