History management
mimosa-project/emwiki pull request #80
Opened 2020-10-15 08:04 UTC by etmula

## 目的
+ 履歴管理機能を追加する

## 関連するIssue等
+ #75 
+ #79 
+ #44 
+ #43 

## レビューポイント
+ 開発環境、本番環境のコンテナ化
+ 使用イメージ

## 留意事項
+ 

## 残課題
+

2020-10-20 10:21 UTC, aabaa requested changes

2020-10-20 10:21 UTC, aabaa commented on emwiki/contents/article/views.py
> +    repo = git.Repo(LOCAL_COMMENT_REPOSITORY_DIR)
MizfileクラスをArticleクラスにマージする

2020-10-20 10:21 UTC, aabaa commented on emwiki/contents/contents/management/commands/generate.py
> +from django.core.management.base import BaseCommand
ファイル名変更 generate.py -> generate_files.py

2020-10-20 10:21 UTC, aabaa commented on emwiki/contents/contents/management/commands/register.py
> +from django.core.management.base import BaseCommand
ファイル名変更 register.py -> register_db.py

2020-10-25 10:58 UTC, etmula commented on emwiki/contents/article/tests/test_article_builder.py
> +from emwiki.settings import TEST_COMMENTED_MIZFILE_DIR, TEST_COMMENTED_MIZFILE_DIR
テキスト処理のテスト用としてTEST_RAW_MIZFILEが必要だったので残してあります

2020-10-25 10:58 UTC, etmula commented
修正完了しました。
レビューお願いします。

2020-10-26 04:26 UTC, merged